name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Build Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up AKS context
        run: |
          az aks get-credentials --resource-group <resource-group> --name <aks-cluster>

      - name: Deploy to AKS
        run: |
          kubectl set image deployment/sample-app sample-app=<acr-name>.azurecr.io/sample-app:${{ github.sha }}
