name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Build Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Install kubelogin
        run: |
          curl -LO https://github.com/Azure/kubelogin/releases/download/v0.0.12/kubelogin-linux-amd64.zip
          unzip kubelogin-linux-amd64.zip
          sudo mv bin/linux_amd64/kubelogin /usr/local/bin/

      - name: Set up AKS context
        run: |
          az aks get-credentials --resource-group vinodrg --name vinodaks

      - name: Deploy to AKS
        run: |
          kubectl set image deployment/samplemicroservice samplemicroservice=vinodacrgh.azurecr.io/samplemicroservice:${{ github.sha }}
